### 입출력과 사칙연산 	#2588

In [1]:
x = int(input())
y = int(input())
z = str(y)
print(x*int(str(y)[2]))
print(x*int(str(y)[1]))
print(x*int(str(y)[0]))
print(x*y)


2360
3776
1416
181720


In [ ]:
m, n = map(int, input().split())

print(f'3: {m * ((n // 1) % 10)}')          # (n // 10 ** 0) % 10
print(f'4: {m * ((n // 10) % 10)}')         # (n // 10 ** 1) % 10
print(f'5: {m * ((n // 100) % 10)}')        # (n // 10 ** 2) % 10
print(f'6: {m * n}')

### 반복문 -		#25304

In [4]:
X = int(input())
N = int(input())
sum = 0
for _ in range(N):
    a, b = map(int, input().split())
    sum += a * b
if 1 <= X <= 1000000000 and 1 <= N <=100 and 1 <= a <= 1000000 and 1 <= b <= 10:
    if X == sum:
        print('Yes')
    else:
        print('No')

No


In [4]:
X = int(input())        # 260000
N = int(input())        # 4
receipt = []
for i in range(N):
    a, b = map(int, input().split())
    receipt.append((a, b))

In [5]:
costco_sum = 0
for a, b in receipt:
    costco_sum += a * b
print(costco_sum)

260000


### 1차원 -		#2562

In [7]:
a_list = []
for _ in range(9):
    a = int(input())
    a_list.append(a)
print(max(a_list))
print(a_list.index(max(a_list))+1)

85
8


In [6]:
c = [3, 29, 38, 12, 57, 74, 40, 85, 61]
cmax, cindex = -1, -1
for index, element in enumerate(c):
    if cmax < element:
        cmax = element
        cindex = index
print(f'index = {cindex}, {cindex+1}번째 값, {cmax}')

index = 7, 8번째 값, 85


### 문자열 -		#2675, #10809, #2908

In [10]:
# 2657
T = int(input())
for _ in range(T):
    R, S = input().split()
    for s_1 in S:
        print(f'{s_1*int(R)}',end='')
    print()

AAABBBCCC
/////HHHHHTTTTTPPPPP


In [7]:
T = int(input())
test_case = []
for _ in range(T):
    cmd = input().split()
    test_case.append(cmd)
print(test_case)

ValueError: invalid literal for int() with base 10: ''

In [8]:
for R, S in test_case:
    result = ''
    r = int(R)
    for s in S:
        result += s * r
    print(result)

NameError: name 'test_case' is not defined

In [14]:
#10809
Alpha = 'abcdefghijklmnopqrstuvwxyz'
S = input()
for a_1 in Alpha:
    print(S.find(a_1), end=' ')


1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [9]:
chr(ord('a') + 1)

'b'

In [10]:
char_dict = {}
for i in range(26):
    c = chr(ord('a') + i)
    char_dict[c] = -1
print(char_dict)

{'a': -1, 'b': -1, 'c': -1, 'd': -1, 'e': -1, 'f': -1, 'g': -1, 'h': -1, 'i': -1, 'j': -1, 'k': -1, 'l': -1, 'm': -1, 'n': -1, 'o': -1, 'p': -1, 'q': -1, 'r': -1, 's': -1, 't': -1, 'u': -1, 'v': -1, 'w': -1, 'x': -1, 'y': -1, 'z': -1}


In [11]:
word = 'baekjoon'
for i in range(26):
    c = chr(ord('a') + i)
    print(word.find(c), end=' ')

1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [12]:
word = 'baekjoon'
char_dict = {}
for i in range(26):
    c = chr(ord('a') + i)
    char_dict[c] = word.find(c)         # find()는 찾는 문자열이 없으면 -1을 리턴함.
print(char_dict)

{'a': 1, 'b': 0, 'c': -1, 'd': -1, 'e': 2, 'f': -1, 'g': -1, 'h': -1, 'i': -1, 'j': 4, 'k': 3, 'l': -1, 'm': -1, 'n': 7, 'o': 5, 'p': -1, 'q': -1, 'r': -1, 's': -1, 't': -1, 'u': -1, 'v': -1, 'w': -1, 'x': -1, 'y': -1, 'z': -1}


In [18]:
#2908
x, y = input().split()
x_1 = int(x[::-1])
y_1 = int(y[::-1])
if x_1 >= y_1:
    print(x_1)
else:
    print(y_1)


938


In [13]:
for i in range(3):
    m, n = input().split()
    m_, n_ = int(m[::-1]), int(n[::-1])
    max_val = m_ if m_ >= n_ else n_
    print(f'{m},{n}: {max_val}')

734,893: 437
221,231: 132
839,237: 938


### 심화 -			#3003, #2444, #1157

In [27]:
#3003
chess_list = list(map(int, input().split()))
chess_piece_list = [1, 1, 2, 2, 2, 8]
for i in range(6):
        print(chess_piece_list[i]-chess_list[i],end=' ')

1 0 0 0 0 1 

In [14]:
# king, queen, rook, bishop, knight, pawn
chess_pieces = [1, 1, 2, 2, 2, 8]
pieces = list(map(int, input().split()))
for i in range(len(pieces)):
    print(chess_pieces[i] - pieces[i], end=' ')

0 -1 -1 -2 -3 2 

In [2]:
#2444
N = int(input())
for i in range(N):
    print(' ' * (N-i-1),end='')
    print('*' * (2 * i + 1))
for k in range(N-1):
    print(' ' * (k + 1),end='')
    print('*' * (2*N - 3 - 2*k))


    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [17]:
N = 5
for i in range(N):
    line = ' ' * (N - i - 1) + '*' * (2 * i + 1)
    print(line)
for k in range(1, N):
    line = ' ' * k + '*' * ((N - k)*2 - 1)
    print(line)


    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [45]:
#1157
S = input().upper()
alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
alpha_count_list = []
alpha_combined = ''
for a_2 in alpha:
    alpha_count_list.append(S.count(a_2))
for i in range(26):
    if alpha_count_list[i] == max(alpha_count_list):
        alpha_combined += alpha[i]
if len(alpha_combined) > 1:
    print('?')
else:
    print(alpha_combined)
        


?


In [19]:
alpha_dict = {}
S = 'A quick brown fox jumps over the lazy dog'
for i in range(26):
    c = chr(ord('a') + i)
    alpha_dict[c] = S.lower().count(c)
print(alpha_dict)

{'a': 2, 'b': 1, 'c': 1, 'd': 1, 'e': 2, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 1, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


In [20]:
alpha_items = list(alpha_dict.items())
alpha_items.sort(key=lambda x: x[1], reverse=True)
alpha_items[:5]

[('o', 4), ('a', 2), ('e', 2), ('r', 2), ('u', 2)]

### 2차원 -		#2738

In [49]:
#2738
N, M = map(int, input().split())
matrix_a = []
matrix_b = []
for _ in range(N):
    matrix_a_line = list(map(int, input().split()))
    matrix_a.append(matrix_a_line)
for _ in range(N):
    matrix_b_line = list(map(int, input().split()))
    matrix_b.append(matrix_b_line)
for i in range(N):
    for k in range(M):
        print(matrix_a[i][k] + matrix_b[i][k], end=' ')
    print()

4 4 4 
6 6 6 
5 6 100 


In [21]:
A = [[1, 1, 1], [2, 2, 2], [0, 1, 0]]
B = [[3, 3, 3], [4, 4, 4], [5, 5, 100]]
C = []
for i in range(len(A)):
    temp = []
    for k in range(len(A[i])):
        temp.append(A[i][k] + B[i][k])
    C.append(temp)

for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()

4 4 4 
6 6 6 
5 6 100 


In [34]:
C = [[0]*3]*3           # r같은 형식으로 만들면 주소가 같아져 마지막 값이 다른 값을 덮어버림.
for i in range(len(A)):
    for k in range(len(A[i])):
        C[i][k] = A[i][k] + B[i][k]

for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()
    print(id(C[i]))

5 6 100 
2592083813760
5 6 100 
2592083813760
5 6 100 
2592083813760


In [25]:
import numpy as np
A = np.array([[1, 1, 1], [2, 2, 2], [0, 1, 0]])
print(A)

[[1 1 1]
 [2 2 2]
 [0 1 0]]


In [26]:
B = np.array([[3, 3, 3], [4, 4, 4], [5, 5, 100]])
print(B)

[[  3   3   3]
 [  4   4   4]
 [  5   5 100]]


In [27]:
# 벡터화 연산
C = A + B
print(C)

[[  4   4   4]
 [  6   6   6]
 [  5   6 100]]
