In [3]:
from pprint import pprint
x, y = map(int, input().split())
matrix = []
for _ in range(x):
    mines = input()
    mines_row = []
    for mine in mines:
        mines_row.append(mine)
    matrix.append(mines_row)
pprint(matrix, width=50)
padding_matrix = []
top = ['.']*(x+2)
padding_matrix.append(top)
for row in matrix:
    padding_matrix_row = []
    padding_matrix_row.append('.')
    padding_matrix_row.extend(row)
    padding_matrix_row.append('.')
    padding_matrix.append(padding_matrix_row)
padding_matrix.append(top)
pprint(padding_matrix, width=100)
print(id(padding_matrix[0]))
print(id(padding_matrix[1]))
print(id(padding_matrix[2]))
print(id(padding_matrix[3]))
print(id(padding_matrix[4]))

[['*', '.', '.'],
 ['*', '.', '.'],
 ['*', '.', '.']]
[['.', '.', '.', '.', '.'],
 ['.', '*', '.', '.', '.'],
 ['.', '*', '.', '.', '.'],
 ['.', '*', '.', '.', '.'],
 ['.', '.', '.', '.', '.']]
2039320136640
2039320137792
2039320095616
2039320133696
2039320136640


In [5]:
def print_mines(m):
    for row in m:
        for element in row:
            print(element, end=' ')
        print()

In [6]:
import random
row, col = map(int, input().split())
mines = [['*' if random.random() > 0.7 else '.' for _ in range(col)] for _ in range(row)]
print_mines(mines)

. . . . 
* . . * 
. . . . 
. . * * 


In [7]:
pad_mines = [['.'] * (col + 2)]     # 맨 윗줄
for mine_row in mines:
    pad_row = ['.']                    # 맨 윗줄과 아랫줄을 제외한 줄
    pad_row.extend(mine_row)
    pad_row.append('.')
    pad_mines.append(pad_row)
pad_mines.append(['.'] * (col + 2))
print_mines(pad_mines)

. . . . . . 
. . . . . . 
. * . . * . 
. . . . . . 
. . . * * . 
. . . . . . 


In [8]:
final_mines = []
for i in range(1, row+1):
    line = []
    for k in range(1, col+1):
        if pad_mines[i][k] == '*':
            line.append('*')
        else:
            count = (pad_mines[i-1][k-1]=='*') + (pad_mines[i-1][k]=='*') + (pad_mines[i-1][k+1]=='*') + \
                    (pad_mines[i][k-1]=='*')                              + (pad_mines[i][k+1]=='*') + \
                    (pad_mines[i+1][k-1]=='*') + (pad_mines[i+1][k]=='*') + (pad_mines[i+1][k+1]=='*')
            line.append(str(count))
    final_mines.append(line)

print_mines(final_mines)

1 1 1 1 
* 1 1 * 
1 2 3 3 
0 1 * * 


In [2]:
x = '1.jpg'
f"{x.split('.')[0]:0>3s}"

'001'

In [11]:
for i in range(1,3):
    print('*' * i)
for j in range(1,3):
    print(' ' * (2 - j), end='')
    print('*' * j)
for k in range(1,3):
    print(' ' * (k - 1), end='')
    print('*' * (2 + 1 - k))
for l in range(1,3):
    print('*' * (2 - l + 1), end='')

*
**
 *
**
**
 *
**
* 


In [18]:
t = int(input())
for j in range(1,t+1):
    print(' ' * (t - j), end='')
    print('*' * j, end='')
    print('*' * j)
for k in range(1,t+1):
    print(' ' * (k - 1), end='')
    print('*' * (t - k + 1), end='')
    print('*' * (t + 1 - k))

         **
        ****
       ******
      ********
     **********
    ************
   **************
  ****************
 ******************
********************
********************
 ******************
  ****************
   **************
    ************
     **********
      ********
       ******
        ****
         **


In [2]:
row, col = 3, 3
matrix = []
for _ in range(3):
    line = []
    for _ in range(3):
        line.append(0)
    matrix.append(line)

for _ in range(3):
    sum = 0
    for i in range(3):
        if i == 0:
            for k in range(3):
                matrix[i][k] = 1
        elif i == 1:
            for k in range(1):
                matrix[i][k+2] = 1
        elif i == 2:
            for k in range(3):
                matrix[i][k+2] = 1
matrix

[[1, 1, 1], [0, 0, 1], [0, 0, 1]]

In [9]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
a[1, np.array([2, 1, 0])]
b = np.vstack([a[0], a[1, np.array([2, 1, 0])], a[2]])
b

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [10]:
c = np.arange(1, 17).reshape(4, 4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [1]:
import numpy as np
snail = np.zeros((5, 5), dtype=int)
k = 1
print = 5
right = -1
bottom = 0
top = 1
for _ in range(print):
    for _ in range(print):
        right += top
        snail[bottom][right] = k
        k += 1
    print -= 1
    for _ in range(print):
        bottom += top
        snail[bottom][right] = k
        k += 1
    top *= -1
snail

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19,  6],
       [15, 24, 25, 20,  7],
       [14, 23, 22, 21,  8],
       [13, 12, 11, 10,  9]])